# Generated by Django 3.2.9 on 2022-02-28 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='basic_user',
            field=models.OneToOneField(limit_choices_to={'is_freelancer': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='freelanceraccount',
            name='basic_user',
            field=models.OneToOneField(limit_choices_to={'is_freelancer': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
