# Generated by Django 3.2.9 on 2022-03-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220228_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientaccount',
            old_name='district',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='freelanceraccount',
            old_name='district',
            new_name='address',
        ),
    ]
