# Generated by Django 3.2.9 on 2022-03-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220305_0811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelanceraccount',
            old_name='category',
            new_name='field',
        ),
    ]
