# Generated by Django 3.2.9 on 2022-03-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_rename_appliedjobs_proposedjobs'),
        ('users', '0005_rename_category_freelanceraccount_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelanceraccount',
            name='skills',
        ),
        migrations.AddField(
            model_name='freelanceraccount',
            name='skills',
            field=models.ManyToManyField(to='job.Skills'),
        ),
    ]
