# Generated by Django 3.2.9 on 2022-03-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220305_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelanceraccount',
            old_name='field',
            new_name='category',
        ),
    ]
