# Generated by Django 3.2.9 on 2022-04-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_clientaccount_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientaccount',
            old_name='registered_on',
            new_name='registered_date',
        ),
        migrations.RenameField(
            model_name='freelanceraccount',
            old_name='registered_on',
            new_name='registered_date',
        ),
        migrations.AddField(
            model_name='freelanceraccount',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='custom', max_length=255),
        ),
    ]
