# Generated by Django 3.2.9 on 2022-04-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_freelanceraccount_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceraccount',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
