# Generated by Django 3.2.9 on 2022-04-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_clientaccount_registered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceraccount',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
