# Generated by Django 3.2.9 on 2022-04-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20220414_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
