# Generated by Django 3.2.9 on 2022-04-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_clientaccount_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaccount',
            name='age',
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='full_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
