# Generated by Django 3.2.9 on 2022-04-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20220423_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceraccount',
            name='portfolios',
            field=models.ManyToManyField(blank=True, null=True, to='users.Portfolio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'An account with this email already exists.'}, max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
