# Generated by Django 3.2.9 on 2022-04-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20220429_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceraccount',
            name='portfolios',
            field=models.ManyToManyField(blank=True, to='users.Portfolio'),
        ),
    ]
