# Generated by Django 3.2.9 on 2022-05-21 04:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20220502_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='slug',
            field=models.SlugField(default=uuid.UUID('182d1f18-da23-4832-a61d-8f2d2df1348d'), unique=True),
        ),
        migrations.AlterField(
            model_name='freelanceraccount',
            name='slug',
            field=models.SlugField(default=uuid.UUID('94ca97f3-6b15-4c88-855c-7fcc0d9172d6'), unique=True),
        ),
    ]
