# Generated by Django 3.2.9 on 2022-02-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='job',
            name='district',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_verified',
        ),
    ]
