# Generated by Django 3.2.9 on 2022-03-05 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220301_1521'),
        ('job', '0005_auto_20220304_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.clientaccount'),
        ),
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants', models.ManyToManyField(to='users.FreelancerAccount')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
            options={
                'verbose_name': 'Proposals',
                'verbose_name_plural': 'Proposals',
            },
        ),
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='users.freelanceraccount')),
                ('jobs', models.ManyToManyField(to='job.Job')),
            ],
            options={
                'verbose_name': 'Applied Job',
                'verbose_name_plural': 'Applied Jobs',
            },
        ),
    ]
