# Generated by Django 3.2.9 on 2022-03-08 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_rename_appliedjobs_proposedjobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='announced_on',
            new_name='announced_date',
        ),
    ]
