# Generated by Django 3.2.9 on 2022-03-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_rename_announced_on_job_announced_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_price',
            field=models.PositiveIntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='min_price',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
