# Generated by Django 3.2.9 on 2022-04-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20220308_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
