# Generated by Django 3.2.9 on 2022-04-17 05:28

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to=job.models.category_pimage_upload),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
