# Generated by Django 3.2.9 on 2022-04-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_auto_20220417_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='freelancer_title',
            field=models.CharField(default='asd', max_length=50),
            preserve_default=False,
        ),
    ]
