# Generated by Django 3.2.9 on 2022-04-23 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20220423_1226'),
        ('job', '0016_category_freelancer_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('proposant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.freelanceraccount')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
            },
        ),
        migrations.DeleteModel(
            name='Proposals',
        ),
    ]
