# Generated by Django 3.2.9 on 2022-04-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_auto_20220423_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
