# Generated by Django 3.2.9 on 2022-04-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_auto_20220425_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='description',
            new_name='proposal',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='title',
        ),
    ]
