# Generated by Django 3.2.9 on 2022-04-29 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20220429_1340'),
        ('job', '0021_auto_20220425_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.clientaccount'),
        ),
    ]
