# Generated by Django 3.2.9 on 2022-07-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_auto_20220501_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
